name: contextos
run-name: ¡Estoy aprendiendo a usar diferentes Contextos!
on:
    push:
    pull_request:
        types: [opened, synchronize, reopened]
    issues:
        types: [opened, edited, closed, labeled]
    issue_comment: 
        types:  [created, deleted]
jobs:
    inicializar:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Imprimiendo Contextos
              run: |
                echo "Contexto Github: ${{ github }}"
