name: expresiones
run-name: ¡Estoy aprendiendo a usar diferentes Expreciones!
on:
    push:
    pull_request:
        types: [opened, synchronize, reopened]
    issues:
        types: [opened, edited, closed, labeled]
    issue_comment: 
        types:  [created, deleted]
jobs:
    informacion-evento:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Imprimir Informacion del Evento
              run: |
                echo "Tipo de Evento: ${{ github.event_name }}"
    evento-push:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        steps:
            - name: Job Push
              run: echo "Se hizo un push"
    evento-issue:
        if: ${{ github.event_name == 'issues' }}
        runs-on: ubuntu-latest
        steps:
            - name: Job Issue
              run: |
                echo "Ha se disparado una accion de un Issue"
                echo "Tipo de evento de Issue: ${{ github.event.action }}"
    evento-issue_comment:
        if: ${{ github.event_name == 'issue_comment' }}
        runs-on: ubuntu-latest
        steps:
            - name: Job Issue Comment
              run: |
                echo "Ha se disparado una accion de un Issue Comment"
    