name: triggers #Nombre del Workflow
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on: 
  push:
    branches:
      - 'aprendiendo-github-actions'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.ts'
  issues:
    types:
      - [opened, closed, labeled]
jobs: #Definicions de los Jobs
  steps-triggers: #Nombre del Job
    runs-on: ubuntu-latest #Donde se va ejecutar
    steps: #Listado de Steps
      - name: "Paso Común a Todos los Triggers"
        run: echo "Este paso se ejecuta siempre"